steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/dashboard-performance-comercial:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/$PROJECT_ID/dashboard-performance-comercial:latest'

images:
  - 'gcr.io/$PROJECT_ID/dashboard-performance-comercial:latest'